apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podname }}
  label:
   team: kaizen
spec:
  containers:
  - name: hello-world
    image: {{ .Values.repository.image }}: {{ .Values.repository.tag }}
