apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    team: kaizen
  ports:
    - protocol: TCP
      port: {{ .Values.sevice.port }}
      targetPort: {{ .Values.service.targetport }}
  type: {{ .Vslues.service.type }}
